# Generated by Django 4.2 on 2023-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propanflaske',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikkelnummer_nykjop', models.CharField(max_length=50)),
                ('artikkelnummer_fylling', models.CharField(max_length=50)),
                ('beskrivelse', models.CharField(max_length=255)),
                ('materiale', models.CharField(max_length=255)),
                ('ventil', models.CharField(max_length=50)),
                ('diameter', models.IntegerField()),
                ('hoyde', models.IntegerField()),
                ('gassmengde', models.IntegerField()),
                ('taravekt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('totalvekt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bilde_id', models.IntegerField()),
            ],
        ),
    ]
