# Generated by Django 4.2 on 2023-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propanflaske',
            name='NOBB_fylling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propanflaske',
            name='NOBB_nykjop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propanflaske',
            name='artikkelnummer_fylling',
            field=models.TextField(),
        ),
    ]
