# Generated by Django 4.2 on 2023-04-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenfuels_noder', '0003_alter_greenfuelsnodes_geo_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenfuelsnodes',
            old_name='company',
            new_name='location',
        ),
    ]
