# Generated by Django 4.2 on 2023-05-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendanorNode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('retailer_id', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255)),
                ('serialno', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, default='', max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('postcity', models.CharField(max_length=255)),
                ('state', models.CharField(default='', max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('geo_lat', models.CharField(max_length=255)),
                ('geo_lng', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VendanorProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('picture_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_long', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VendanorNodesInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('count', models.JSONField()),
                ('location', models.CharField(max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer_automater.vendanornode')),
            ],
            options={
                'unique_together': {('node', 'product_id')},
            },
        ),
    ]
