# Generated by Django 4.2 on 2023-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenFuelsNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('postcity', models.CharField(max_length=200)),
                ('geo_lat', models.FloatField()),
                ('geo_lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VendanorNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('postcity', models.CharField(max_length=200)),
                ('geo_lat', models.FloatField()),
                ('geo_lng', models.FloatField()),
            ],
        ),
    ]
