# Generated by Django 4.2 on 2023-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forhandlere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendanornodes',
            name='serialno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
