# Generated by Django 4.2 on 2023-04-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forhandlere', '0003_vendanornodeinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendanorNodeInventory',
        ),
    ]
