# Generated by Django 4.2 on 2023-05-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forhandlere', '0004_delete_vendanornodeinventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendanorNodes',
            new_name='VendanorNode',
        ),
    ]
