# Generated by Django 4.2 on 2023-05-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forhandlere', '0005_rename_vendanornodes_vendanornode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendanorNode',
            new_name='VendanorNodes',
        ),
    ]
